package controllers;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import models.LastFmUser;
import models.Playlist;
import models.Track;

import org.apache.commons.lang.StringUtils;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

import controllers.util.LastFmParameterBuilder;

import play.Logger;
import play.Play;
import play.cache.Cache;
import play.libs.Codec;
import play.libs.WS;
import play.libs.WS.HttpResponse;
import play.libs.WS.WSRequest;
import play.mvc.Before;
import play.mvc.Controller;
import play.mvc.Util;

public class Application extends Controller {


    static String _token;
    
    @Before(unless={"login","lcallback","home"})
    static void before(){
        Logger.info("request.action: %s",request.action);
        Logger.info("request.actionMethod: %s",request.actionMethod);
        if(Cache.get(session.getId()) == null){
            Logger.info("redirectiong to login() ...");
            login();
        }
        request.args.put("user",Cache.get(session.getId()));
    }
    public static void setVolume(int volume){
        session.put("volume", volume > 100 ? 100 : (volume < 0  ? 0 : volume));
    }
    public static void home(){
        render();
    }
    public static void radio(){
        LastFmUser user = getUser();
        String url = "http://ws.audioscrobbler.com/2.0/";
        String station = "lastfm://user/" + user.getName() + "/library";
        String method = "radio.tune";
        Map<String, Object> params = LastFmParameterBuilder.newInstance()
                              .add("station",station)
                              .add("method", method)
                              .add("sk", user.getKey()).build(true);
        
        WSRequest wsRequest = WS.withEncoding("utf-8").url(url);
        wsRequest.parameters = params;
        HttpResponse httpResponse = wsRequest.post();
        Logger.info("radio.tune : %s", httpResponse.getString());
        //TODO:error
//        api_key (Required) : A Last.fm API key.
//        api_sig (Required) : A Last.fm method signature. See authentication for more information.
//        sk (Required) : A session key generated by authenticating a user via the authentication protocol.
        Playlist playlist = getPlayList(user.getKey());
        user.setPlaylist(playlist);
        render(user);
    }
    
    
    public static void lcallback() throws NoSuchAlgorithmException, IOException {
        final String token = params.get("token");
        _token = token; 
        final String method = "auth.getSession";
        
        TreeMap<String, String> map = new TreeMap<String , String>(){{
          put("api_key", LastFmParameterBuilder.api_key);
          put("method", method);
          put("token", token);
        }};
        WSRequest wsRequest = WS.withEncoding("UTF-8").url(
        String.format("http://ws.audioscrobbler.com/2.0/?method=%s&api_key=%s&api_sig=%s&token=%s", method,LastFmParameterBuilder.api_key, LastFmParameterBuilder.api_sig(map), token,LastFmParameterBuilder.api_secret));
        Logger.info("url: "+wsRequest.url);
        HttpResponse httpResponse = wsRequest.get();
        Logger.info(httpResponse.getString());
        Document xml = httpResponse.getXml();
        if("failed".equalsIgnoreCase(xml.getElementsByTagName("lfm").item(0).getAttributes().getNamedItem("status").getNodeValue())){
            flash.error("login failed");
            flash.keep();
            home();
        }else{
            Node sessionNode = xml.getElementsByTagName("session").item(0);
            String name =((Element) sessionNode).getElementsByTagName("name").item(0).getTextContent();
            String key=((Element) sessionNode).getElementsByTagName("key").item(0).getTextContent();
            int subs =Integer.parseInt(((Element) sessionNode).getElementsByTagName("subscriber").item(0).getTextContent());
            if(subs == 0){
                flash.error("you are not a subscriber");
                flash.keep();
                home();
            }
            LastFmUser user = LastFmUser.create(name,key,subs);
            Cache.add(session.getId(), user);
        }
        radio();
    }
    
    public static void login() {
        redirect("http://www.last.fm/api/auth/?api_key=ef1b8ec486144479aea70cc1bb73a7d5&cb="+getCallBack("/application/lcallback"));
    }
    
    @Util
    private static String getCallBack(String resource){
        return (Play.id == null || Play.id.isEmpty()) ? "http://localhost:9000"+resource : "http://livelast.herokuapp.com"+resource;
    }

    @Util
    private static LastFmUser getUser(){
        return (LastFmUser) request.args.get("user");
    }
    
    public static void tag(String tag) {
        if(tag == null || tag.isEmpty()){
            index();
        }
        LastFmUser user = getUser();
        String url = "http://ws.audioscrobbler.com/2.0/";
        String station = "lastfm://globaltags/"+tag;
        String method = "radio.tune";
        Map<String, Object> params = LastFmParameterBuilder.newInstance()
                              .add("station",station)
                              .add("method", method)
                              .add("sk", user.getKey()).build(true);
        
        WSRequest wsRequest = WS.withEncoding("utf-8").url(url);
        wsRequest.parameters = params;
        HttpResponse httpResponse = wsRequest.post();
        Logger.info("radio.tune : %s", httpResponse.getString());
        //TODO:error
//        api_key (Required) : A Last.fm API key.
//        api_sig (Required) : A Last.fm method signature. See authentication for more information.
//        sk (Required) : A session key generated by authenticating a user via the authentication protocol.
        if(user.getPlaylist()!= null){
            user.getPlaylist().clear();
        }
        Playlist playlist = getPlayList(user.getKey());
        user.setPlaylist(playlist);
        renderArgs.put("user", user);
        renderTemplate("/Application/radio.html");
    }
    
    public static void index() {
        LastFmUser user = getUser();
        String url = "http://ws.audioscrobbler.com/2.0/";
        String station = "lastfm://user/" + user.getName() + "/library";
        String method = "radio.tune";
        Map<String, Object> params = LastFmParameterBuilder.newInstance()
                              .add("station",station)
                              .add("method", method)
                              .add("sk", user.getKey()).build(true);
        
        WSRequest wsRequest = WS.withEncoding("utf-8").url(url);
        wsRequest.parameters = params;
        HttpResponse httpResponse = wsRequest.post();
        Logger.info("radio.tune : %s", httpResponse.getString());
        //TODO:error
//        api_key (Required) : A Last.fm API key.
//        api_sig (Required) : A Last.fm method signature. See authentication for more information.
//        sk (Required) : A session key generated by authenticating a user via the authentication protocol.
        Playlist playlist = getPlayList(user.getKey());
        user.setPlaylist(playlist);
        render(user);
    }
    @Util
    private static Playlist getPlayList(final String sk){
        String url = "http://ws.audioscrobbler.com/2.0/";
        String method = "radio.getPlaylist";
        Map<String, Object> parameters = LastFmParameterBuilder.newInstance().add("method", method)
                                            .add("sk", sk).build(true);
        WSRequest wsRequest = WS.withEncoding("utf-8").url(url);
        wsRequest.parameters = parameters;
        HttpResponse httpResponse = wsRequest.post();
        Logger.info("radio.getPlayList:" + httpResponse.getString());
        //
        Playlist playlist = new Playlist();
        
        Document xml = httpResponse.getXml();
        Element _playlist = ((Element)xml.getElementsByTagName("playlist").item(0));
        playlist.title = (_playlist.getElementsByTagName("title").item(0)).getTextContent();
        playlist.creator = (_playlist.getElementsByTagName("creator").item(0)).getTextContent();
        
        Element _trackList = ((Element)xml.getElementsByTagName("trackList").item(0));
        NodeList tracks = _trackList.getElementsByTagName("track");
        for (int i = 0; i < tracks.getLength(); i++) {
            Track track = new Track();
            track.location = ((Element)tracks.item(i)).getElementsByTagName("location").item(0).getTextContent();
            track.title =((Element)tracks.item(i)).getElementsByTagName("title").item(0).getTextContent();
            track.album = ((Element)tracks.item(i)).getElementsByTagName("album").item(0).getTextContent();
            track.image = ((Element)tracks.item(i)).getElementsByTagName("image").item(0).getTextContent();
            track.duration = Long.valueOf(((Element)tracks.item(i)).getElementsByTagName("duration").item(0).getTextContent());
            track.creator = ((Element)tracks.item(i)).getElementsByTagName("creator").item(0).getTextContent();
            playlist.tracks.add(track);
        }
        
        //
        return playlist;
    }

    public static void nextTrack(){
        long now = Calendar.getInstance().getTimeInMillis();
        if( ! request.isAjax()){
            notFound();
        }
        LastFmUser user = getUser();
        boolean userIsReady = user.getPlaylist() != null; 
        Track track = null;
        try{
            if(!userIsReady){
                user.setPlaylist(getPlayList(user.getKey()));
            }
            track = user.getPlaylist().next();
        }catch(IndexOutOfBoundsException e){
            user.setPlaylist(getPlayList(user.getKey()));
            track = user.getPlaylist().next();
        }finally{
            nowPlaying();
        }
        Track prev = user.getPlaylist().prevTrack();
        if(prev != null){
            if(now -  prev.playedAt > prev.duration / 2 ){
                scrobble(prev);
            }
        }
        renderJSON(track);
    }
    
    @Util
    private static void scrobble(Track prev) {
//        artist[i] (Required) : The artist name.
//        track[i] (Required) : The track name.
//        timestamp[i] (Required) : The time the track started playing, in UNIX timestamp format (integer number of seconds since 00:00:00, January 1st 1970 UTC). This must be in the UTC time zone.
//        api_key (Required) : A Last.fm API key.
//        api_sig (Required) : A Last.fm method signature. See authentication for more information.
//        sk (Required) : A session key generated by authenticating a user via the authentication protocol.        
        Map<String, Object> parameters = LastFmParameterBuilder.newInstance()
                              .add("method", "track.scrobble")
                              .add("artist[0]", prev.creator)
                              .add("track[0]", prev.title)
                              .add("timestamp[0]", String.valueOf((int) (prev.playedAt / 1000)))
                              .add("sk",getUser().getKey()).build(true);
        String url = "http://ws.audioscrobbler.com/2.0/";
        WSRequest wsRequest = WS.withEncoding("utf-8").url(url);
        wsRequest.parameters = parameters;
        HttpResponse httpResponse = wsRequest.post();
        Logger.info("track.scrobble:" + httpResponse.getString());
        
    }

    @Util
    private static void nowPlaying(){
        LastFmUser user = getUser();
        Track track = user.getPlaylist().getCurrentTrack();
        track.playedAt = Calendar.getInstance().getTimeInMillis();
//        artist (Required) : The artist name.
//        track (Required) : The track name.
//        api_key (Required) : A Last.fm API key.
//        api_sig (Required) : A Last.fm method signature. See authentication for more information.
//        sk (Required) : A session key generated by authenticating a user via the authentication protocol.
        final String method = "track.updateNowPlaying";
        final String artist = track.creator;
        final String album = track.album;
        final String sk = user.getKey();
        final String _track = track.title;
        Map<String, Object> parameters = LastFmParameterBuilder.newInstance()
                .add("method", method)
                .add("sk", sk)
                .add("artist", artist)
                .add("album", album)
                .add("track", _track)
                .build(true);
         String url = "http://ws.audioscrobbler.com/2.0/";
         WSRequest wsRequest = WS.withEncoding("utf-8").url(url);
         wsRequest.parameters = parameters;
         HttpResponse httpResponse = wsRequest.post();
         Logger.info(method + " :" + httpResponse.getString());
        
    }
    
    public static void love(){
        //track.love
//        track (Required) : A track name (utf8 encoded)
//        artist (Required) : An artist name (utf8 encoded)
//        api_key (Required) : A Last.fm API key.
//        api_sig (Required) : A Last.fm method signature. See authentication for more information.
//        sk (Required) : A session key generated by authenticating a user via the authentication protocol.
        Track track = getUser().getPlaylist().getCurrentTrack();
        Map<String, Object> parameters = LastFmParameterBuilder.newInstance()
                              .add("method", "track.love")
                              .add("track", track.title)
                              .add("artist", track.creator)
                              .add("sk", getUser().getKey()).build(true);
        String url = "http://ws.audioscrobbler.com/2.0/";
        WSRequest wsRequest = WS.withEncoding("utf-8").url(url);
        wsRequest.parameters = parameters;
        HttpResponse httpResponse = wsRequest.post();
        Logger.info("track.love" + " :" + httpResponse.getString());
        renderJSON(track.title + " loved");
    }
    
}